site_name: Ashesttt's Blog
#site_url: https://Ashesttt.github.io
site_author: Ashesttt
repo_name: 'Ashesttt/Ashesttt.github.io'
repo_url: https://github.com/Ashesttt/Ashesttt.github.io
copyright: "Copyright &copy; 2024 - 2024 JiHao Huang"



theme:
  name: 'material'
  language: 'zh'
  logo: shuzai.png
  palette:
    primary: light blue
    accent: pink
  features:
    - content.code.select
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer  
  
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Ashesttt'
markdown_extensions:
  - github-callouts # github callouts 语法支持
  - admonition # 注解块支持
  - pymdownx.arithmatex # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji: # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist: # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - meta # 元数据支持
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
plugins:
  - search
